### ISSUE TITLE
Choosing a License & Discord

### ISSUE THREAD

**Issue by FrostyCirno** [notrogan/FirstPersonDeath#1]
Hello! Very Fun Mod. I have some suggestions for you.

I would choose a license for your mod to have. I would choose from one found on https://opensource.org/licenses?categories=international%2Cpopular-strong-community. These are open source, allowing people to see how the mod works & lets others continue updating the mod after you stop.

I would also set up a post under "mod-releases" in the Lethal Company Modding Discord server https://discord.gg/lcmod. Joining gives your mod a lot of traction, allowing you to be in contact with users / other mod developers.

Please keep working on this!

**Comment by notrogan** [comment]
Hello! Glad you're enjoying it, and thanks for the suggestions.

I went ahead and added a MIT license (seems like what im looking for, but maybe theres a better one) so that shouldn't be a problem anymore.

As for the Discord, I'll probably look into it eventually but it's not exactly a priority. Most likely I'll make a post once I get the code polished to a level I'm happy with... theres still some aspects that I think could be refined.
